version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./../:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    image: php:7.2-fpm
    volumes:
      - ./../:/var/www/html

  composer:
    image: "composer"
    volumes:
      - ./../:/app
    command: install

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    expose:
        - "27017"

  mongo-express:
    image: mongo-express
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin